export const ALERT = "ALERT";
export const GET_REGISTRATION_FORM = "GET_REGISTRATION_FORM";
export const ADD_STUDENT_FIELD = "ADD_STUDENT_FIELD";
export const ADD_COURSE_FIELD = "ADD_COURSE_FIELD";
export const ADD_FIELD = "ADD_FIELD";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const LOGOUT = "LOGOUT";
export const RESET_ATTEMPT = "RESET_ATTEMPT";
export const REMOVE_FIELD = "REMOVE_FIELD";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";
export const FILTER_EVENT = "FILTER_EVENT";
export const SUBMIT_INITIATED = "SUBMIT_INITIATED";
export const RESET_SUBMIT_STATUS = "RESET_SUBMIT_STATUS";
export const GET = "get";
export const POST = "post";
export const PATCH = "patch";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_COURSE_STARTED = "FETCH_COURSES_STARTED";
export const FETCH_COURSE_SUCCESSFUL = "FETCH_COURSES_SUCCESSFUL";
export const FETCH_COURSE_FAILED = "FETCH_COURSES_FAILED";

export const FETCH_INSTRUCTOR_STARTED = "FETCH_INSTRUCTORS_STARTED";
export const FETCH_INSTRUCTOR_SUCCESSFUL = "FETCH_INSTRUCTORS_SUCCESSFUL";
export const FETCH_INSTRUCTOR_FAILED = "FETCH_INSTRUCTORS_FAILED";

export const POST_INSTRUCTOR_STARTED = "POST_INSTRUCTOR_STARTED";
export const POST_INSTRUCTOR_SUCCESSFUL = "POST_INSTRUCTOR_SUCCESSFUL";
export const POST_INSTRUCTOR_FAILED = "POST_INSTRUCTOR_FAILED";

export const PATCH_INSTRUCTOR_STARTED = "PATCH_INSTRUCTOR_STARTED";
export const PATCH_INSTRUCTOR_SUCCESSFUL = "PATCH_INSTRUCTOR_SUCCESSFUL";
export const PATCH_INSTRUCTOR_FAILED = "PATCH_INSTRUCTOR_FAILED";

export const FETCH_STUDENT_STARTED = "FETCH_STUDENT_STARTED";
export const FETCH_STUDENT_SUCCESSFUL = "FETCH_STUDENT_SUCCESSFUL";
export const FETCH_STUDENT_FAILED = "FETCH_STUDENT_FAILED";

export const FETCH_PARENT_STARTED = "FETCH_PARENT_STARTED";
export const FETCH_PARENT_SUCCESSFUL = "FETCH_PARENT_SUCCESSFUL";
export const FETCH_PARENT_FAILED = "FETCH_PARENT_FAILED";

export const FETCH_ENROLLMENT_STARTED = "FETCH_ENROLLMENT_STARTED";
export const FETCH_ENROLLMENT_SUCCESSFUL = "FETCH_ENROLLMENT_SUCCESSFUL";
export const FETCH_ENROLLMENT_FAILED = "FETCH_ENROLLMENT_FAILED";

export const FETCH_NOTE_STARTED = "FETCH_NOTE_STARTED";
export const FETCH_NOTE_SUCCESSFUL = "FETCH_NOTE_SUCCESSFUL";
export const FETCH_NOTE_FAILED = "FETCH_NOTE_FAILED";

export const PATCH_NOTE_STARTED = "PATCH_NOTE_STARTED";
export const PATCH_NOTE_SUCCESSFUL = "PATCH_NOTE_SUCCESSFUL";
export const PATCH_NOTE_FAILED = "PATCH_NOTE_FAILED";

export const POST_NOTE_STARTED = "POST_NOTE_STARTED";
export const POST_NOTE_SUCCESSFUL = "POST_NOTE_SUCCESSFUL";
export const POST_NOTE_FAILED = "POST_NOTE_FAILED";

export const FETCH_USER_STARTED = "FETCH_USER_STARTED";
export const FETCH_USER_SUCCESSFUL = "FETCH_USER_SUCCESSFUL";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const FETCH_COURSE_NOTE_STARTED = "FETCH_COURSE_NOTE_STARTED";
export const FETCH_COURSE_NOTE_SUCCESSFUL = "FETCH_COURSE_NOTE_SUCCESSFUL";
export const FETCH_COURSE_NOTE_FAILED = "FETCH_COURSE_NOTE_FAILED";

export const PATCH_COURSE_NOTE_STARTED = "PATCH_COURSE_NOTE_STARTED";
export const PATCH_COURSE_NOTE_SUCCESSFUL = "PATCH_COURSE_NOTE_SUCCESSFUL";
export const PATCH_COURSE_NOTE_FAILED = "PATCH_COURSE_NOTE_FAILED";

export const POST_COURSE_NOTE_STARTED = "POST_COURSE_NOTE_STARTED";
export const POST_COURSE_NOTE_SUCCESSFUL = "POST_COURSE_NOTE_SUCCESSFUL";
export const POST_COURSE_NOTE_FAILED = "POST_COURSE_NOTE_FAILED";

export const POST_STUDENT_SUCCESSFUL = "POST_STUDENT_SUCCESSFUL";
export const POST_STUDENT_FAILED = "POST_STUDENT_FAILED";
export const FETCH_CATEGORIES_SUCCESSFUL = "FETCH_CATEGORY_SUCCESSFUL";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORY_FAILED";
export const POST_PARENT_SUCCESSFUL = "POST_PARENT_SUCCESSFUL";
export const POST_PARENT_FAILED = "POST_PARENT_FAILED";
export const POST_CATEGORY_SUCCESSFUL = "POST_CATEGORY_SUCCESSFUL";
export const POST_CATEGORY_FAILED = "POST_CATEGORY_FAILED";

export const POST_COURSE_STARTED = "POST_COURSE_STARTED";
export const POST_COURSE_SUCCESSFUL = "POST_COURSE_SUCCESSFUL";
export const POST_COURSE_FAILED = "POST_COURSE_FAILED";
export const PATCH_COURSE_SUCCESSFUL = "PATCH_COURSE_SUCCESSFUL";
export const PATCH_COURSE_FAILED = "PATCH_COURSE_FAILED";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const GET_SEARCH_QUERY_SUCCESSFUL = "";
export const GET_SEARCH_QUERY_FAILED = "";

export const GET_ACCOUNT_SEARCH_QUERY_STARTED = "GET_ACCOUNT_SEARCH_QUERY_STARTED";
export const GET_COURSE_SEARCH_QUERY_STARTED = "GET_COURSE_SEARCH_QUERY_STARTED";
export const GET_ACCOUNT_SEARCH_QUERY_SUCCESS = "GET_ACCOUNT_SEARCH_QUERY_SUCCESS";
export const GET_COURSE_SEARCH_QUERY_SUCCESS = "GET_COURSE_SEARCH_QUERY_SUCCESS";
export const GET_ACCOUNT_SEARCH_QUERY_FAILED = "GET_ACCOUNT_SEARCH_QUERY_FAILED";
export const GET_COURSE_SEARCH_QUERY_FAILED = "GET_COURSE_SEARCH_QUERY_FAILED";

export const SET_PARENT = "SET_PARENT";
export const RESET_REGISTRATION = "RESET_REGISTRATION";

export const INIT_COURSE_REGISTRATION = "INIT_COURSE_REGISTRATION";
export const ADD_CLASS_REGISTRATION = "ADD_CLASS_REGISTRATION";
export const ADD_TUTORING_REGISTRATION = "ADD_TUTORING_REGISTRATION";
export const ADD_SMALL_GROUP_REGISTRATION = "ADD_SMALL_GROUP_REGISTRATION";
export const EDIT_COURSE_REGISTRATION = "EDIT_COURSE_REGISTRATION";

export const UPDATE_SEARCH_FILTER = "UPDATE_SEARCH_FILTER";
