export const ALERT = "ALERT";
export const GET_REGISTRATION_FORM = "GET_REGISTRATION_FORM";
export const ADD_STUDENT_FIELD = "ADD_STUDENT_FIELD";
export const ADD_COURSE_FIELD = "ADD_COURSE_FIELD";
export const ADD_FIELD = "ADD_FIELD";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const LOGOUT = "LOGOUT";
export const RESET_ATTEMPT = "RESET_ATTEMPT";
export const REMOVE_FIELD = "REMOVE_FIELD";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";
export const FILTER_EVENT = "FILTER_EVENT";
export const SUBMIT_INITIATED = "SUBMIT_INITIATED";
export const RESET_SUBMIT_STATUS = "RESET_SUBMIT_STATUS";
export const GET = "get";
export const POST = "post";
export const PATCH = "patch";
export const DELETE = "delete";
export const IS_SEARCHING = true;
export const NOT_SEARCHING = false;
export const SEARCH_ALL = "all";
export const SEARCH_ACCOUNTS = "account";
export const SEARCH_COURSES = "course";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_COURSE_STARTED = "FETCH_COURSES_STARTED";
export const FETCH_COURSE_SUCCESSFUL = "FETCH_COURSES_SUCCESSFUL";
export const FETCH_COURSE_FAILED = "FETCH_COURSES_FAILED";

export const FETCH_INSTRUCTOR_STARTED = "FETCH_INSTRUCTORS_STARTED";
export const FETCH_INSTRUCTOR_SUCCESSFUL = "FETCH_INSTRUCTORS_SUCCESSFUL";
export const FETCH_INSTRUCTOR_FAILED = "FETCH_INSTRUCTORS_FAILED";

export const POST_INSTRUCTOR_STARTED = "POST_INSTRUCTOR_STARTED";
export const POST_INSTRUCTOR_SUCCESSFUL = "POST_INSTRUCTOR_SUCCESSFUL";
export const POST_INSTRUCTOR_FAILED = "POST_INSTRUCTOR_FAILED";

export const PATCH_INSTRUCTOR_STARTED = "PATCH_INSTRUCTOR_STARTED";
export const PATCH_INSTRUCTOR_SUCCESSFUL = "PATCH_INSTRUCTOR_SUCCESSFUL";
export const PATCH_INSTRUCTOR_FAILED = "PATCH_INSTRUCTOR_FAILED";

export const POST_ADMIN_STARTED = "POST_ADMIN_STARTED";
export const POST_ADMIN_SUCCESSFUL = "POST_ADMIN_SUCCESSFUL";
export const POST_ADMIN_FAILED = "POST_ADMIN_FAILED";

export const PATCH_ADMIN_STARTED = "PATCH_ADMIN_STARTED";
export const PATCH_ADMIN_SUCCESSFUL = "PATCH_ADMIN_SUCCESSFUL";
export const PATCH_ADMIN_FAILED = "PATCH_ADMIN_FAILED";

export const FETCH_STUDENT_STARTED = "FETCH_STUDENT_STARTED";
export const FETCH_STUDENT_SUCCESSFUL = "FETCH_STUDENT_SUCCESSFUL";
export const FETCH_STUDENT_FAILED = "FETCH_STUDENT_FAILED";

export const FETCH_PARENT_STARTED = "FETCH_PARENT_STARTED";
export const FETCH_PARENT_SUCCESSFUL = "FETCH_PARENT_SUCCESSFUL";
export const FETCH_PARENT_FAILED = "FETCH_PARENT_FAILED";

export const FETCH_ENROLLMENT_STARTED = "FETCH_ENROLLMENT_STARTED";
export const FETCH_ENROLLMENT_SUCCESSFUL = "FETCH_ENROLLMENT_SUCCESSFUL";
export const FETCH_ENROLLMENT_FAILED = "FETCH_ENROLLMENT_FAILED";

export const FETCH_ACCOUNT_NOTE_STARTED = "FETCH_ACCOUNT_NOTE_STARTED";
export const FETCH_ACCOUNT_NOTE_SUCCESSFUL = "FETCH_ACCOUNT_NOTE_SUCCESSFUL";
export const FETCH_ACCOUNT_NOTE_FAILED = "FETCH_ACCOUNT_NOTE_FAILED";
export const PATCH_ACCOUNT_NOTE_STARTED = "PATCH_ACCOUNT_NOTE_STARTED";
export const PATCH_ACCOUNT_NOTE_SUCCESSFUL = "PATCH_ACCOUNT_NOTE_SUCCESSFUL";
export const PATCH_ACCOUNT_NOTE_FAILED = "PATCH_ACCOUNT_NOTE_FAILED";
export const POST_ACCOUNT_NOTE_STARTED = "POST_ACCOUNT_NOTE_STARTED";
export const POST_ACCOUNT_NOTE_SUCCESSFUL = "POST_ACCOUNT_NOTE_SUCCESSFUL";
export const POST_ACCOUNT_NOTE_FAILED = "POST_ACCOUNT_NOTE_FAILED";

export const FETCH_USER_STARTED = "FETCH_USER_STARTED";
export const FETCH_USER_SUCCESSFUL = "FETCH_USER_SUCCESSFUL";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const FETCH_COURSE_NOTE_STARTED = "FETCH_COURSE_NOTE_STARTED";
export const FETCH_COURSE_NOTE_SUCCESSFUL = "FETCH_COURSE_NOTE_SUCCESSFUL";
export const FETCH_COURSE_NOTE_FAILED = "FETCH_COURSE_NOTE_FAILED";
export const PATCH_COURSE_NOTE_STARTED = "PATCH_COURSE_NOTE_STARTED";
export const PATCH_COURSE_NOTE_SUCCESSFUL = "PATCH_COURSE_NOTE_SUCCESSFUL";
export const PATCH_COURSE_NOTE_FAILED = "PATCH_COURSE_NOTE_FAILED";
export const POST_COURSE_NOTE_STARTED = "POST_COURSE_NOTE_STARTED";
export const POST_COURSE_NOTE_SUCCESSFUL = "POST_COURSE_NOTE_SUCCESSFUL";
export const POST_COURSE_NOTE_FAILED = "POST_COURSE_NOTE_FAILED";

export const FETCH_ENROLLMENT_NOTE_STARTED = "FETCH_ENROLLMENT_NOTE_STARTED";
export const FETCH_ENROLLMENT_NOTE_SUCCESSFUL = "FETCH_ENROLLMENT_NOTE_SUCCESSFUL";
export const FETCH_ENROLLMENT_NOTE_FAILED = "FETCH_ENROLLMENT_NOTE_FAILED";
export const PATCH_ENROLLMENT_NOTE_STARTED = "PATCH_ENROLLMENT_NOTE_STARTED";
export const PATCH_ENROLLMENT_NOTE_SUCCESSFUL = "PATCH_ENROLLMENT_NOTE_SUCCESSFUL";
export const PATCH_ENROLLMENT_NOTE_FAILED = "PATCH_ENROLLMENT_NOTE_FAILED";
export const POST_ENROLLMENT_NOTE_STARTED = "POST_ENROLLMENT_NOTE_STARTED";
export const POST_ENROLLMENT_NOTE_SUCCESSFUL = "POST_ENROLLMENT_NOTE_SUCCESSFUL";
export const POST_ENROLLMENT_NOTE_FAILED = "POST_ENROLLMENT_NOTE_FAILED";

export const POST_STUDENT_SUCCESSFUL = "POST_STUDENT_SUCCESSFUL";
export const POST_STUDENT_FAILED = "POST_STUDENT_FAILED";
export const FETCH_CATEGORIES_SUCCESSFUL = "FETCH_CATEGORY_SUCCESSFUL";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORY_FAILED";
export const POST_PARENT_SUCCESSFUL = "POST_PARENT_SUCCESSFUL";
export const POST_PARENT_FAILED = "POST_PARENT_FAILED";

export const POST_COURSE_STARTED = "POST_COURSE_STARTED";
export const POST_COURSE_SUCCESSFUL = "POST_COURSE_SUCCESSFUL";
export const POST_COURSE_FAILED = "POST_COURSE_FAILED";
export const PATCH_COURSE_STARTED = "PATCH_COURSE_STARTED";
export const PATCH_COURSE_SUCCESSFUL = "PATCH_COURSE_SUCCESSFUL";
export const PATCH_COURSE_FAILED = "PATCH_COURSE_FAILED";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const GET_SEARCH_QUERY_SUCCESSFUL = "";
export const GET_SEARCH_QUERY_FAILED = "";

export const GET_ACCOUNT_SEARCH_QUERY_STARTED = "GET_ACCOUNT_SEARCH_QUERY_STARTED";
export const GET_COURSE_SEARCH_QUERY_STARTED = "GET_COURSE_SEARCH_QUERY_STARTED";
export const GET_ACCOUNT_SEARCH_QUERY_SUCCESS = "GET_ACCOUNT_SEARCH_QUERY_SUCCESS";
export const GET_COURSE_SEARCH_QUERY_SUCCESS = "GET_COURSE_SEARCH_QUERY_SUCCESS";
export const GET_ACCOUNT_SEARCH_QUERY_FAILED = "GET_ACCOUNT_SEARCH_QUERY_FAILED";
export const GET_COURSE_SEARCH_QUERY_FAILED = "GET_COURSE_SEARCH_QUERY_FAILED";

export const SET_PARENT = "SET_PARENT";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const RESET_REGISTRATION = "RESET_REGISTRATION";

export const INIT_COURSE_REGISTRATION = "INIT_COURSE_REGISTRATION";
export const CLOSE_COURSE_REGISTRATION = "CLOSE_COURSE_REGISTRATION";
export const ADD_CLASS_REGISTRATION = "ADD_CLASS_REGISTRATION";
export const ADD_TUTORING_REGISTRATION = "ADD_TUTORING_REGISTRATION";
export const ADD_SMALL_GROUP_REGISTRATION = "ADD_SMALL_GROUP_REGISTRATION";
export const EDIT_COURSE_REGISTRATION = "EDIT_COURSE_REGISTRATION";

export const UPDATE_SEARCH_FILTER = "UPDATE_SEARCH_FILTER";

export const POST_ENROLLMENT_STARTED = "POST_ENROLLMENT_STARTED";
export const POST_ENROLLMENT_SUCCESS = "POST_ENROLLMENT_SUCCESS";
export const POST_ENROLLMENT_FAILED = "POST_ENROLLMENT_FAILED";

export const POST_TUTORING_ENROLLMENT_STARTED = "POST_TUTORING_ENROLLMENT_STARTED";
export const POST_TUTORING_ENROLLMENT_SUCCESS = "POST_TUTORING_ENROLLMENT_SUCCESS";
export const POST_TUTORING_ENROLLMENT_FAILED = "POST_TUTORING_ENROLLMENT_FAILED";

export const POST_CATEGORY_STARTED = "POST_CATEGORY_STARTED";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_FAILED = "POST_CATEGORY_FAILED";
export const GET_CATEGORY_STARTED = "GET_CATEGORY_STARTED";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";
export const PATCH_CATEGORY_STARTED = "PATCH_CATEGORY_STARTED";
export const PATCH_CATEGORY_SUCCESS = "PATCH_CATEGORY_SUCCESS";
export const PATCH_CATEGORY_FAILED = "PATCH_CATEGORY_FAILED";

export const POST_PRICE_RULE_STARTED = "POST_PRICE_RULE_STARTED";
export const POST_PRICE_RULE_SUCCESS = "POST_PRICE_RULE_SUCCESS";
export const POST_PRICE_RULE_FAILED = "POST_PRICE_RULE_FAILED";

export const GET_PRICE_RULE_STARTED = "GET_PRICE_RULE_STARTED";
export const GET_PRICE_RULE_SUCCESS = "GET_PRICE_RULE_SUCCESS";
export const GET_PRICE_RULE_FAILED = "GET_PRICE_RULE_FAILED";

export const PATCH_PRICE_RULE_STARTED = "PATCH_PRICE_RULE_STARTED";
export const PATCH_PRICE_RULE_SUCCESS = "PATCH_PRICE_RULE_SUCCESS";
export const PATCH_PRICE_RULE_FAILED = "PATCH_PRICE_RULE_FAILED";

export const GET_PRICE_QUOTE_STARTED = "GET_PRICE_QUOTE_STARTED";
export const GET_PRICE_QUOTE_SUCCESS = "GET_PRICE_QUOTE_SUCCESS";
export const GET_PRICE_QUOTE_FAILED = "GET_PRICE_QUOTE_FAILED";

export const POST_DISCOUNT_DATE_RANGE_START = "POST_DISCOUNT_DATE_RANGE_START";
export const POST_DISCOUNT_DATE_RANGE_SUCCESS = "POST_DISCOUNT_DATE_RANGE_SUCCESS";
export const POST_DISCOUNT_DATE_RANGE_FAILED = "POST_DISCOUNT_DATE_RANGE_FAILED";

export const POST_DISCOUNT_MULTI_COURSE_STARTED = "POST_DISCOUNT_MULTI_COURSE_STARTED";
export const POST_DISCOUNT_MULTI_COURSE_SUCCESS = "POST_DISCOUNT_MULTI_COURSE_SUCCESS";
export const POST_DISCOUNT_MULTI_COURSE_FAILED = "POST_DISCOUNT_MULTI_COURSE_FAILED";

export const POST_DISCOUNT_PAYMENT_METHOD_STARTED = "POST_DISCOUNT_PAYMENT_METHOD_STARTED";
export const POST_DISCOUNT_PAYMENT_METHOD_SUCCESS = "POST_DISCOUNT_PAYMENT_METHOD_SUCCESS";
export const POST_DISCOUNT_PAYMENT_METHOD_FAILED = "POST_DISCOUNT_PAYMENT_METHOD_FAILED";

export const GET_DISCOUNT_DATE_RANGE_START = "GET_DISCOUNT_DATE_RANGE_START";
export const GET_DISCOUNT_DATE_RANGE_SUCCESS = "GET_DISCOUNT_DATE_RANGE_SUCCESS";
export const GET_DISCOUNT_DATE_RANGE_FAILED = "GET_DISCOUNT_DATE_RANGE_FAILED";

export const GET_DISCOUNT_MULTI_COURSE_STARTED = "GET_DISCOUNT_MULTI_COURSE_STARTED";
export const GET_DISCOUNT_MULTI_COURSE_SUCCESS = "GET_DISCOUNT_MULTI_COURSE_SUCCESS";
export const GET_DISCOUNT_MULTI_COURSE_FAILED = "GET_DISCOUNT_MULTI_COURSE_FAILED";

export const GET_DISCOUNT_PAYMENT_METHOD_STARTED = "GET_DISCOUNT_PAYMENT_METHOD_STARTED";
export const GET_DISCOUNT_PAYMENT_METHOD_SUCCESS = "GET_DISCOUNT_PAYMENT_METHOD_SUCCESS";
export const GET_DISCOUNT_PAYMENT_METHOD_FAILED = "GET_DISCOUNT_PAYMENT_METHOD_FAILED";

export const DELETE_DISCOUNT_PAYMENT_METHOD_STARTED = "DELETE_DISCOUNT_PAYMENT_METHOD_STARTED";
export const DELETE_DISCOUNT_PAYMENT_METHOD_SUCCESS = "DELETE_DISCOUNT_PAYMENT_METHOD_SUCCESS";
export const DELETE_DISCOUNT_PAYMENT_METHOD_FAILED = "DELETE_DISCOUNT_PAYMENT_METHOD_FAILED";

export const DELETE_DISCOUNT_MULTI_COURSE_STARTED = "DELETE_DISCOUNT_MULTI_COURSE_STARTED";
export const DELETE_DISCOUNT_MULTI_COURSE_SUCCESS = "DELETE_DISCOUNT_MULTI_COURSE_SUCCESS";
export const DELETE_DISCOUNT_MULTI_COURSE_FAILED = "DELETE_DISCOUNT_MULTI_COURSE_FAILED";

export const DELETE_DISCOUNT_DATE_RANGE_STARTED = "DELETE_DISCOUNT_DATE_RANGE_STARTED";
export const DELETE_DISCOUNT_DATE_RANGE_SUCCESS = "DELETE_DISCOUNT_DATE_RANGE_SUCCESS";
export const DELETE_DISCOUNT_DATE_RANGE_FAILED = "DELETE_DISCOUNT_DATE_RANGE_FAILED";

export const PATCH_DISCOUNT_MULTI_COURSE_STARTED = "DELETE_DISCOUNT_MULTI_COURSE_STARTED";
export const PATCH_DISCOUNT_MULTI_COURSE_SUCCESS = "PATCH_DISCOUNT_MULTI_COURSE_SUCCESS";
export const PATCH_DISCOUNT_MULTI_COURSE_FAILED = "PATCH_DISCOUNT_MULTI_COURSE_FAILED";

export const PATCH_DISCOUNT_PAYMENT_METHOD_STARTED = "PATCH_DISCOUNT_PAYMENT_METHOD_STARTED";
export const PATCH_DISCOUNT_PAYMENT_METHOD_SUCCESS = "PATCH_DISCOUNT_PAYMENT_METHOD_SUCCESS";
export const PATCH_DISCOUNT_PAYMENT_METHOD_FAILED = "PATCH_DISCOUNT_PAYMENT_METHOD_FAILED";

export const PATCH_DISCOUNT_DATE_RANGE_STARTED = "PATCH_DISCOUNT_DATE_RANGE_STARTED";
export const PATCH_DISCOUNT_DATE_RANGE_SUCCESS = "PATCH_DISCOUNT_DATE_RANGE_SUCCESS";
export const PATCH_DISCOUNT_DATE_RANGE_FAILED = "PATCH_DISCOUNT_DATE_RANGE_FAILED";

export const GET_SESSIONS_STARTED = "GET_SESSIONS_STARTED";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_FAILED = "GET_SESSIONS_FAILED";

export const PATCH_SESSION_STARTED = "PATCH_SESSION_STARTED";
export const PATCH_SESSION_SUCCESS = "PATCH_SESSION_SUCCESS";
export const PATCH_SESSION_FAILED = "PATCH_SESSION_FAILED";

export const FETCH_OOO_STARTED = "FETCH_OOO_STARTED";
export const FETCH_OOO_SUCCESS = "FETCH_OOO_SUCCESS";
export const FETCH_OOO_FAILED = "FETCH_OOO_FAILED";
export const POST_OOO_SUCCESS = "POST_OOO_SUCCESS";

export const FETCH_INSTRUCTORAVAILABILITY_STARTED = "FETCH_INSTRUCTORAVAILABILITY_STARTED";
export const FETCH_INSTRUCTORAVAILABILITY_SUCCESS = "FETCH_INSTRUCTORAVAILABILITY_SUCCESS";
export const FETCH_INSTRUCTORAVAILABILITY_FAILED = "FETCH_INSTRUCTORAVAILABILITY_FAILED";
export const POST_INSTRUCTORAVAILABILITY_SUCCESS = "POST_INSTRUCTORAVAILABILITY_SUCCESS";

export const FETCH_INSTRUCTOR_AVAILABILITY_SUCCESS = "FETCH_INSTRUCTOR_AVAILABILITY_SUCCESS";

export const POST_PAYMENT_SUCCESS = "POST_PAYMENT_SUCCESS";

export const SET_REGISTRATION = "SET_REGISTRATION";
export const COMPLETE_REGISTRATION = "COMPLETE_REGISTRATION";

export const GET_PAYMENT_PARENT_SUCCESS = "GET_PAYMENT_PARENT_SUCCESS";

export const GET_PAYMENT_STARTED = "GET_PAYMENT_STARTED";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILED = "GET_PAYMENT_FAILED";

export const GET_PAYMENT_ENROLLMENT_SUCCESS = "GET_PAYMENT_ENROLLMENT_SUCCESS";

export const UPDATE_SEARCH_STATUS = "UPDATE_SEARCH_STATUS";
export const UPDATE_PRIMARY_SEARCH_FILTER = "UPDATE_PRIMARY_SEARCH_FILTER";

export const RESET_SEARCH_PARAMS = "REST_SEARCH_PARAMS";

export const RESET_SCHEDULER_STATUS = "RESET_SCHEDULER_STATUS";

export const GET_UNPAID_STARTED = "GET_UNPAID_STARTED";
export const GET_UNPAID_FAILED = "GET_UNPAID_FAILED";
export const GET_UNPAID_SUCCESS = "GET_UNPAID_SUCCESS";
export const DELETE_ENROLLMENT_STARTED = "DELETE_ENROLLMENT_STARTED";
export const DELETE_ENROLLMENT_SUCCESS = "DELETE_ENROLLMENT_SUCCESS";
export const DELETE_ENROLLMENT_FAILED = "DELETE_ENROLLMENT_FAILED";
