export const ALERT = "ALERT";
export const GET_REGISTRATION_FORM = "GET_REGISTRATION_FORM";
export const ADD_STUDENT_FIELD = "ADD_STUDENT_FIELD";
export const ADD_COURSE_FIELD = "ADD_COURSE_FIELD";
export const ADD_FIELD = "ADD_FIELD";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const LOGOUT = "LOGOUT";
export const RESET_ATTEMPT = "RESET_ATTEMPT";
export const REMOVE_FIELD = "REMOVE_FIELD";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";
export const FILTER_EVENT = "FILTER_EVENT";
export const SUBMIT_INITIATED = "SUBMIT_INITIATED";
export const RESET_SUBMIT_STATUS = "RESET_SUBMIT_STATUS";
export const GET = "get";
export const POST = "post";
export const PATCH = "patch";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_COURSES_STARTED = "FETCH_COURSES_STARTED";
export const FETCH_COURSES_SUCCESSFUL = "FETCH_COURSES_SUCCESSFUL";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

export const FETCH_INSTRUCTORS_STARTED = "FETCH_INSTRUCTORS_STARTED";
export const FETCH_INSTRUCTORS_SUCCESSFUL = "FETCH_INSTRUCTORS_SUCCESSFUL";
export const FETCH_INSTRUCTORS_FAILED = "FETCH_INSTRUCTORS_FAILED";

export const FETCH_STUDENTS_STARTED = "FETCH_STUDENTS_STARTED";
export const FETCH_STUDENTS_SUCCESSFUL = "FETCH_STUDENTS_SUCCESSFUL";
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED";

export const POST_STUDENT_SUCCESSFUL = "POST_STUDENT_SUCCESSFUL";
export const POST_STUDENT_FAILED = "POST_STUDENT_FAILED";
export const FETCH_PARENTS_SUCCESSFUL = "FETCH_PARENTS_SUCCESSFUL";
export const FETCH_PARENTS_FAILED = "FETCH_PARENTS_FAILED";
export const FETCH_CATEGORIES_SUCCESSFUL = "FETCH_CATEGORY_SUCCESSFUL";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORY_FAILED";
export const POST_PARENT_SUCCESSFUL = "POST_PARENT_SUCCESSFUL";
export const POST_PARENT_FAILED = "POST_PARENT_FAILED";
export const POST_INSTRUCTOR_SUCCESSFUL = "POST_INSTRUCTOR_SUCCESSFUL";
export const POST_INSTRUCTOR_FAILED = "POST_INSTRUCTOR_FAILED";
export const POST_CATEGORY_SUCCESSFUL = "POST_CATEGORY_SUCCESSFUL";
export const POST_CATEGORY_FAILED = "POST_CATEGORY_FAILED";
export const POST_COURSE_SUCCESSFUL = "POST_COURSE_SUCCESSFUL";
export const POST_COURSE_FAILED = "POST_COURSE_FAILED";
