export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const ALERT = 'ALERT';
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const GET_REGISTRATION_FORM = 'GET_REGISTRATION_FORM';
export const ADD_STUDENT_FIELD = 'ADD_STUDENT_FIELD';
export const  RAND_COLOR = 'RAND_COLOR';