import {DELETE, GET, PATCH, POST} from "../actions/actionTypes";

export default {
    "Authentication": initAuth(),
    "RegistrationForms": initRegistrationForm(),
    "SignUpForm": initSignUpForm(),
    "Course": {
        "CourseCategories": [],
        "NewCourseList": {},
        "CourseSessions": {},
    },
    "Enrollments": {},
    "Payments": {},
    "Users": {
        "StudentList": {},
        "ParentList": {},
        "ReceptionistList": {
            101: {
                user_id: 101,
                name: "Ryan Liou",
                phone_number: "1234567899",
                email: "ryan.liou@gmail.com",
                role: 'receptionist',
                birthday: "11/5/1985",
                action_log: {
                    1: {
                        date: "6/22/2018",
                        time: "2:00PM",
                        description: "Unregistered English 7 sessions with Danny Hong",
                    },
                    2: {
                        date: "6/10/2018",
                        time: "5:00PM",
                        description: "Registered AP Calc tutoring with Daniel Huang",
                    },
                    3: {
                        date: "6/2/2018",
                        time: "5:00PM",
                        description: "Registered AP Calc tutoring with Daniel Huang",
                    },
                    4: {
                        date: "5/24/2018",
                        time: "5:00PM",
                        description: "Registered AP Calc tutoring with Daniel Huang",
                    },
                },
            },
        },
        "InstructorList": {},
    },
    "CalendarData": {
        "CourseSessions": "",
    },
    "RequestStatus": initRequests(),
    "SearchResults": {
        SearchQuery:{},
        searchQueryStatus: "",
        accounts: [],
        courses: [],
        filter: {
            account:{
                profile:"",
                grade:"",
                sort:"",
            },
            course:{
                course:"",
                availability:"",
                sort:"",
            }
        }
    },
    "Admin":{
        PriceRules: [],
        Discounts: {
            MultiCourse: [],
            DateRange: [],
            PaymentMethod: [],
        },
    }
};

function initRequests() {
    return {
        "admin": {
            [GET]: {},
            [PATCH]: {},
        },
        "course": {
            [GET]: {},
            [PATCH]: {},
        },
        "category": {
            [GET]: {},
            [PATCH]: {},
        },
        "instructor": {
            [GET]: {},
            [PATCH]: {},
        },
        "parent": {
            [GET]: {},
            [PATCH]: {},
        },
        "student": {
            [GET]: {},
            [PATCH]: {},
        },
        "schedule": {
            [GET]: {},
            [PATCH]: {},
        },
        "enrollment": {
            [GET]: {},
            [PATCH]: {},
        },
        "accountNote": {
            [GET]: {},
            [PATCH]: {},
        },
        "courseNote": {
            [GET]: {},
            [PATCH]: {},
        },
        "enrollmentNote": {
            [GET]: {},
            [PATCH]: {},
        },
        "priceRule":{
            [GET]: {},
            [PATCH]: {},
            [POST]: {},
        },
        "discount":{
            "dateRange":{
                [GET]: {},
                [POST]: {},
            },
            "multiCourse":{
                [GET]: {},
                [PATCH]: {},
                [POST]: {},
            },
            "paymentMethod":{
                [GET]: {},
                [POST]: {},

            },
            [DELETE]:"",
            [PATCH]: "",
        },
        "registration":{
            "enrollment":{
                [POST]:{},
            }
        },
        "registeringParent":"",
    };
}

function initAuth() {
    return {
        token: null,
        isAdmin: false,
    };
}

function initRegistrationForm() {
    const studentInfoSection = {
        "Student Information": [
            {
                field: "Current Instructor in School",
                name: "Current Instructor in School",
                type: "short text",
                conditional: false,
                required: false,
                full: true,
                field_limit: 1,
            },
            {
                field: "Textbook Used",
                name: "Textbook Used",
                type: "short text",
                conditional: false,
                required: false,
                full: true,
                field_limit: 1,
            },
            {
                field: "Current Grade in Class",
                name: "Current Grade in Class",
                type: "short text",
                conditional: false,
                required: false,
                full: false,
                field_limit: 1,
            },
            {
                field: "Current Topic in School / Topic of Interest",
                name: "Current Topic in School / Topic of Interest",
                type: "short text",
                conditional: false,
                required: false,
                full: true,
                field_limit: 1,
            },
            {
                field: "Student Strengths",
                name: "Student Strengths",
                type: "short text",
                conditional: false,
                required: false,
                full: true,
                field_limit: 1,
            },
            {
                field: "Student Weaknesses",
                name: "Student Weaknesses",
                type: "short text",
                conditional: false,
                required: false,
                full: true,
                field_limit: 1,
            },
        ],
    };
    const parentInfoSection = {
        "Parent Information": [
            {
                field: "Select Parent",
                name: "Select Parent",
                type: "select parent",
                field_limit: 1,
                required: false,
                full: false,
            },
            {
                field: "Parent First Name",
                name: "Parent First Name",
                type: "short text",
                field_limit: 1,
                required: false,
                full: true,
            },
            {
                field: "Parent Last Name",
                name: "Parent Last Name",
                type: "short text",
                field_limit: 1,
                required: false,
                full: true,
            },
            {
                field: "Relationship to Student",
                name: "Relationship to Student",
                type: "select",
                required: false,
                field_limit: 1,
                options: ["Mother", "Father", "Guardian", "Other"],
            },
            {
                field: "Gender",
                name: "Gender",
                type: "select",
                options: ["Do not disclose", "Male", "Female"],
                required: false,
                field_limit: 1,
            },
            {
                field: "Parent Email",
                name: "Parent Email",
                type: "email",
                field_limit: 1,
                required: false,
                full: true,
            },
            {
                field: "Parent Phone Number",
                name: "Phone Number",
                type: "phone number",
                field_limit: 1,
                required: false,
                full: true,
            },

            {
                field: "Parent Birthday",
                name: "Parent Birthday",
                type: "date",
                field_limit: 1,
                required: false,
                full: true,
            },
            {
                field: "Address",
                name: "Address",
                type: "short text",
                full: false,
                required: false,
                field_limit: 1,
            },
            {
                field: "City",
                name: "City",
                type: "short text",
                full: false,
                required: false,
                field_limit: 1,
            },
            {
                field: "State",
                name: "State",
                type: "short text",
                suggestions: [
                    {label: "AL"}, {label: "AK"}, {label: "AZ"}, {label: "AR"}, {label: "CA"}, {label: "CO"},
                    {label: "CT"}, {label: "DE"}, {label: "FL"}, {label: "GA"}, {label: "HI"}, {label: "ID"},
                    {label: "IL"}, {label: "IN"}, {label: "IA"}, {label: "KS"},
                    {label: "KY"}, {label: "KY"}, {label: "LA"}, {label: "ME"}, {label: "MD"}, {label: "MA"}, {label: "MI"},
                    {label: "MS"}, {label: "MO"}, {label: "MT"}, {label: "NE"}, {label: "NV"}, {label: "NH"}, {label: "NJ"},
                    {label: "NM"}, {label: "NY"}, {label: "NC"}, {label: "ND"},
                    {label: "OH"}, {label: "OK"}, {label: "OR"}, {label: "PA"}, {label: "RI"}, {label: "SC"}, {label: "SD"},
                    {label: "TN"}, {label: "TX"}, {label: "UT"}, {label: "VT"}, {label: "VA"}, {label: "WA"}, {label: "WV"}, {label: "WI"},
                    {label: "WY"},
                ].map((suggestion) => ({
                    value: suggestion.label,
                    label: suggestion.label,
                })),
                full: false,
                required: false,
                field_limit: 1,
            },
            {
                field: "Zip Code",
                name: "Zip Code",
                type: "string",
                full: false,
                required: false,
                field_limit: 1,
            },
        ],
    };
    const courseInfoQuestions = [
        {
            field: "Course Name",
            name: "Course Name",
            type: "short text",
            conditional: false,
            required: true,
            full: true,
            field_limit: 1,
        },
        {
            field: "Description",
            name: "Description",
            type: "short text",
            multiline: true,
            conditional: false,
            required: false,
            full: true,
            field_limit: 1,
        },
        {
            field: "Instructor",
            name: "Instructor",
            type: "instructor",
            conditional: false,
            required: false,
            full: true,
            field_limit: 1,
        },
        {
            field: "Category",
            name: "Category",
            type: "category",
            options: [],
            conditional: false,
            required: true,
            full: false,
            field_limit: 1,
        },
        {
            field: "Grade Level",
            name: "Grade Level",
            type: "select",
            options: ["Elementary School", "Middle School","High School", "College"],
            conditional: false,
            required: true,
            full: false,
            field_limit: 1,
        },
        {
            field: "Start Date",
            name: "Start Date",
            type: "date",
            conditional: false,
            required: false,
            full: false,
            field_limit: 1,
        },
        {
            field: "Start Time",
            name: "Start Time",
            type: "time",
            conditional: false,
            required: true,
            full: false,
            field_limit: 1,
        },
        {
            field: "Duration",
            name: "Duration",
            type: "select",
            options:
                ["1 Hour", "1.5 Hours", "0.5 Hours", "2 Hours"],
            conditional: false,
            required: true,
            full: false,
            field_limit: 1,
        },
        {
            field: "Number of Weekly Sessions",
            name: "Number of Weekly Sessions",
            type: "number",
            conditional: false,
            required: true,
            full: false,
            field_limit: 1,
        },
        {
            field: "Capacity",
            name: "Capacity",
            type: "number",
            conditional: false,
            required: false,
            full: false,
            field_limit: 1,
        }
    ];
    return {
        registration_form: {
            student: {
                form_type: "student",
                section_titles: ["Basic Information", "Parent Information"],
                "Basic Information": [
                    {
                        field: "Student First Name",
                        name: "Student First Name",
                        type: "short text",
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Student Last Name",
                        name: "Student Last Name",
                        type: "short text",
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Gender",
                        name: "Gender",
                        type: "select",
                        options: ["Do not disclose", "Male", "Female"],
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Grade",
                        name: "Grade",
                        type: "number",
                        required: false,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Birthday",
                        name: "Birthday",
                        type: "date",
                        required: false,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "School",
                        name: "School",
                        type: "short text",
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Student Phone Number",
                        name: "Student Phone Number",
                        type: "phone number",
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                ],
                ...parentInfoSection,
            },
            parent: {
                form_type: "parent",
                section_titles: ["Parent Information"],
                "Parent Information": [
                    {
                        field: "First Name",
                        name: "First Name",
                        type: "short text",
                        field_limit: 1,
                        required: true,
                        full: true,
                    },
                    {
                        field: "Last Name",
                        name: "Last Name",
                        type: "short text",
                        field_limit: 1,
                        required: true,
                        full: true,
                    },
                    {
                        field: "Relationship to Student(s)",
                        name: "Relationship to Student(s)",
                        type: "select",
                        required: false,
                        field_limit: 1,
                        options: ["Mother", "Father", "Guardian", "Other"],
                    },
                    {
                        field: "Gender",
                        name: "Gender",
                        type: "select",
                        options: ["Do not disclose", "Male", "Female"],
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Email",
                        name: "Email",
                        type: "email",
                        field_limit: 1,
                        required: false,
                        full: true,
                    },
                    {
                        field: "Birthday",
                        name: "Birthday",
                        type: "date",
                        field_limit: 1,
                        required: false,
                        full: true,
                    },
                    {
                        field: "Parent Phone Number",
                        name: "Phone Number",
                        type: "phone number",
                        field_limit: 1,
                        required: false,
                        full: true,
                    },
                    {
                        field: "Address",
                        name: "Address",
                        type: "short text",
                        full: false,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "City",
                        name: "City",
                        type: "short text",
                        full: false,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "State",
                        name: "State",
                        type: "short text",
                        suggestions: [
                            { label: "AL" }, { label: "AK" }, { label: "AZ" }, { label: "AR" }, { label: "CA" }, { label: "CO" },
                            { label: "CT" }, { label: "DE" }, { label: "FL" }, { label: "GA" }, { label: "HI" }, { label: "ID" },
                            { label: "IL" }, { label: "IN" }, { label: "IA" }, { label: "KS" },
                            { label: "KY" }, { label: "KY" }, { label: "LA" }, { label: "ME" }, { label: "MD" }, { label: "MA" }, { label: "MI" },
                            { label: "MS" }, { label: "MO" }, { label: "MT" }, { label: "NE" }, { label: "NV" }, { label: "NH" }, { label: "NJ" },
                            { label: "NM" }, { label: "NY" }, { label: "NC" }, { label: "ND" },
                            { label: "OH" }, { label: "OK" }, { label: "OR" }, { label: "PA" }, { label: "RI" }, { label: "SC" }, { label: "SD" },
                            { label: "TN" }, { label: "TX" }, { label: "UT" }, { label: "VT" }, { label: "VA" }, { label: "WA" }, { label: "WV" }, { label: "WI" },
                            { label: "WY" },
                        ].map((suggestion) => ({
                            value: suggestion.label,
                            label: suggestion.label,
                        })),
                        full: false,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Zip Code",
                        name: "Zip Code",
                        type: "string",
                        full: false,
                        required: false,
                        field_limit: 1,
                    },
                ],
            },
            tutoring: {
                form_type: "tutoring",
                section_titles: [ "Student", "Student Information", "Tutor Selection", "Schedule", "Tuition Quote Tool"],
                "Student": [
                    {
                        field: "Student",
                        name: "Student",
                        type: "student",
                        conditional: false,
                        required: false,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Grade Level",
                        name: "Grade Level",
                        type: "select",
                        options: ["Elementary School", "Middle School","High School", "College"],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    ]
                ,
                ...studentInfoSection,
                "Tutor Selection": [
                    {
                        field: "Instructor",
                        name: "Instructor",
                        type: "instructor",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Course Name",
                        name: "Course Name",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Category",
                        name: "Category",
                        type: "category",
                        options: [],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
                "Schedule": [
                    {
                        field: "Start Date",
                        name: "Start Date",
                        type: "date",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Session Start Time",
                        name: "Session Start Time",
                        type: "time",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Duration",
                        name: "Duration",
                        type: "select",
                        options:
                            ["1 Hour", "1.5 Hours", "0.5 Hours", "2 Hours"],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Number of Sessions",
                        name: "Number of Sessions",
                        type: "number",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
                "Tuition Quote Tool": [
                    {
                        field: "Price Quote",
                        name: "Price Quote",
                        type: "price quote",
                        conditional: false,
                        required: false,
                        full: false,
                        field_limit: 1,
                    }
                ]
            },
            course: {
                form_type: "course",
                section_titles: ["Student", "Student Information", "Course Selection"],
                "Student": [
                    {
                        field: "Student",
                        name: "Student",
                        type: "student",
                        conditional: false,
                        required: false,
                        full: false,
                        field_limit: 5,
                    },
                ],
                ...studentInfoSection,
                "Course Selection": [
                    {
                        field: "Course",
                        name: "Course",
                        type: "course",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 5,
                    },
                ],
            },
            instructor: {
                form_type: "instructor",
                section_titles: ["Basic Information", "Education", "Experience"],
                "Basic Information": [
                    {
                        field: "First Name",
                        name: "First Name",
                        type: "short text",
                        conditional: false,
                        required: true,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Last Name",
                        name: "Last Name",
                        type: "short text",
                        conditional: false,
                        required: true,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "E-Mail",
                        name: "E-Mail",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Phone Number",
                        name: "Phone Number",
                        type: "phone number",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Gender",
                        name: "Gender",
                        type: "select",
                        options:
                            ["Do not disclose", "Male", "Female"],
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Address",
                        name: "Address",
                        type: "address",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "City",
                        name: "City",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Zip Code",
                        name: "Zip Code",
                        type: "zipcode",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "State",
                        name: "State",
                        type: "select",
                        options: [
                            "Please select a State", "AL", "AK", "AZ", "AR", "CA", "CO",
                            "CT", "DE", "FL", "GA", "HI", "ID",
                            "IL", "IN", "IA", "KS",
                            "KY", "KY", "LA", "ME", "MD", "MA", "MI",
                            "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                            "NM", "NY", "NC", "ND",
                            "OH", "OK", "OR", "PA", "RI", "SC", "SD",
                            "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
                            "WY",
                        ],
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Date of Birth (MM/DD/YYYY)",
                        name: "Date of Birth",
                        type: "date",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                ],
                "Education": [
                    {
                        field: "College",
                        name: "College",
                        type: "short text",
                        full: true,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Degree(s)",
                        name: "Degree(s)",
                        type: "short text",
                        full: true,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Minor(s)",
                        name: "Minor(s)",
                        type: "short text",
                        full: true,
                        required: false,
                        field_limit: 1,
                    },
                ],
                "Experience": [
                    {
                        field: "Subject(s) Tutor Can Teach",
                        name: "Subject(s) Tutor Can Teach",
                        type: "string",
                        full: true,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Specialties",
                        name: "Specialties",
                        type: "string",
                        full: true,
                        required: false,
                        field_limit: 1,
                    },
                    {
                        field: "Background",
                        name: "Background",
                        type: "string",
                        full: true,
                        required: false,
                        field_limit: 1,
                        multiline: true,
                    },
                    {
                        field: "Notes",
                        name: "Notes",
                        type: "string",
                        full: true,
                        required: false,
                        field_limit: 1,
                        multiline: true,
                    },
                ],
            },
            course_details: {
                form_type: "course_details",
                section_titles: ["Course Info", "Tuition"],
                "Course Info": courseInfoQuestions,
                "Tuition": [
                    {
                        field: "Tuition",
                        name: "Tuition",
                        type: "number",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    }
                ]
            },
            small_group: {
                form_type:"small_group",
                section_titles: [ "Student", "Group Type", "Group Details", "Tuition Quote Tool"],
                "Student":[
                    {
                        field: "Student",
                        name: "Student",
                        type: "student",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
                "Group Type":[
                    {
                        field: "Group Type",
                        name: "Select Group Type",
                        type: "select",
                        options:
                            ["Existing Small Group", "New Small Group"],
                        conditional: true,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
                "Group Details":{
                    "Existing Small Group":[
                        {
                            field: "Select Group",
                            name: "Select Group",
                            type: "course",
                            conditional: false,
                            required: true,
                            full: false,
                            field_limit: 1,
                        }
                    ],
                    "New Small Group": courseInfoQuestions,
                },
                "Tuition Quote Tool": [
                    {
                        field: "Price Quote",
                        name: "Price Quote",
                        type: "price quote",
                        conditional: false,
                        required: false,
                        full: false,
                        field_limit: 1,
                    }
                ]
            },
            pricing: {
                form_type: "pricing",
                section_titles: [ "Pricing" ],
                "Pricing":[
                    {
                        field: "Price Rule Name",
                        name: "Price Rule Name",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Category",
                        name: "Category",
                        type: "category",
                        options: [],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Select Grade",
                        name: "Select Grade",
                        type: "select",
                        options: ["Elementary School", "Middle School","High School", "College"],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Select Course Size",
                        name: "Select Course Size",
                        type: "select",
                        options: ["Tutoring", "Small Group"],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Set Hourly Tuition ($)",
                        name: "Set Hourly Tuition ($)",
                        type: "number",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
            },
            discount: {
                form_type: "discount",
                section_titles: ["Discount Description", "Discount Rules", "Discount Amount"],
                "Discount Description":[
                    {
                        field: "Discount Name",
                        name: "Discount Name",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Discount Description",
                        name: "Discount Description",
                        type: "short text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Discount Type",
                        name: "Discount Type",
                        type: "select",
                        options:[
                            "Bulk Order Discount",
                            "Date Range Discount",
                            "Payment Method Discount",
                        ],
                        conditional: true,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                ],
                "Discount Rules": {
                        "Bulk Order Discount":[
                            {
                                field: "Minimum number of sessions",
                                name: "Minimum number of sessions",
                                type: "number",
                                conditional: false,
                                required: true,
                                full: false,
                                field_limit: 1,
                            },
                        ],
                        "Date Range Discount":[
                            {
                                field: "Discount Start Date",
                                name: "Discount Start Date",
                                type: "date",
                                conditional: false,
                                required: true,
                                full: false,
                                field_limit: 1,
                            },
                            {
                                field: "Discount End Date",
                                name: "Discount End Date",
                                type: "date",
                                conditional: false,
                                required: true,
                                full: false,
                                field_limit: 1,
                            },
                        ],
                        "Payment Method Discount":[
                            {
                                field: "Payment Method",
                                name: "Payment Method",
                                type: "select",
                                options:[
                                    "Cash",
                                    "Check",
                                    "Credit Card",
                                    "International Credit Card",
                                ],
                                conditional: false,
                                required: true,
                                full: false,
                                field_limit: 1,
                            },
                        ],
                    },
                "Discount Amount": [
                    {
                        field: "Discount Type",
                        name: "Discount Type",
                        type: "select",
                        options:["Percent", "Fixed"],
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    },
                    {
                        field: "Discount Amount",
                        name: "Discount Amount",
                        type: "number",
                        conditional: false,
                        required: true,
                        full: false,
                        field_limit: 1,
                    }
                ],
            },
            course_category: {
                form_type: "course_category",
                section_titles: [ "Category Details" ],
                "Category Details":[
                    {
                        field: "Category Name",
                        name: "Category Name",
                        type: "text",
                        conditional: false,
                        required: true,
                        full: true,
                        field_limit: 1,
                    },
                    {
                        field: "Description",
                        name: "Description",
                        type: "text",
                        conditional: false,
                        required: false,
                        full: true,
                        field_limit: 1,
                    },
                ]
            },
        },
        submitStatus: null,
        CurrentParent: "",
        registered_courses: null,
    };
}

function initSignUpForm() {
    return {

    };
}
