name: Lint

on: [push, pull_request]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: gimenete/eslint-action@master
            with:
                repo-token: ${{secrets.GITHUB_TOKEN}}
